// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Closing — сервис Wails, через который интерфейс сообщает, что буфер записан.
 * 
 * Нужен, потому что несохранённое живёт в вебвью, и Go его оттуда не достанет:
 * единственный способ — попросить и дождаться (SPEC §6, хук WindowClosing).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Ready вызывается из интерфейса, когда буфер записан.
 * 
 * Экспортируется в биндинги — это единственный способ для вебвью ответить.
 */
export function Ready(): $CancellablePromise<void> {
    return $Call.ByID(4139240713);
}

/**
 * Wait просит интерфейс сохраниться и ждёт ответа, но не дольше таймаута.
 * 
 * Возвращает false, если ответа не дождались: тогда закрываемся всё равно.
 * Потерять при этом можно только правки последних миллисекунд, а зависшее окно
 * пользователь видит сразу.
 */
export function Wait(): $CancellablePromise<boolean> {
    return $Call.ByID(1609368823);
}
