// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Git — сервис Wails: как часто правки уезжают в историю.
 * 
 * Настройка живёт в интерфейсе (config.json) и приезжает сюда вызовом, а не
 * читается Go напрямую: config.json для Go непрозрачен, и разбирать его в двух
 * местах значит однажды разойтись.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CommitNow фиксирует накопленное немедленно.
 */
export function CommitNow(): $CancellablePromise<void> {
    return $Call.ByID(2097132874);
}

/**
 * Configure задаёт окно автокоммита в секундах. Ноль — коммитить сразу.
 * 
 * Переключение вниз, на немедленный коммит, сначала сбрасывает накопленное:
 * иначе пачка, собранная при старой настройке, повисла бы до закрытия окна.
 */
export function Configure(seconds: number): $CancellablePromise<$models.GitSettings> {
    return $Call.ByID(1364525069, seconds);
}

/**
 * SetEnabled включает или выключает историю в этом хранилище.
 * 
 * Выключение не трогает уже накопленные коммиты: репозиторий остаётся на
 * диске, приложение просто перестаёт в него писать.
 */
export function SetEnabled(enabled: boolean): $CancellablePromise<$models.GitSettings> {
    return $Call.ByID(1888994842, enabled);
}

/**
 * Settings возвращает состояние истории.
 */
export function Settings(): $CancellablePromise<$models.GitSettings> {
    return $Call.ByID(1449516574);
}
