// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info — сервис Wails: сведения о хранилище и о самой программе.
 * 
 * Только чтение и одна операция пересборки индекса. Ничего из этого не меняет
 * заметки, поэтому сервис отделён от Notes: там операции над данными человека,
 * здесь справка.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notes$0 from "../notes/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Build отдаёт сведения о сборке.
 */
export function Build(): $CancellablePromise<$models.Build> {
    return $Call.ByID(3772233619);
}

/**
 * OnBattery — работает ли машина от батареи.
 * 
 * Через `pmset`, потому что чистого способа спросить об этом из Go без cgo
 * нет, а cgo-зависимость ради одной строки ломает сборку universal binary
 * (CLAUDE.md, раздел про зависимости). Ошибка означает «не от батареи»: это
 * безопасная сторона — прозрачность просто не отключится.
 */
export function OnBattery(): $CancellablePromise<boolean> {
    return $Call.ByID(4108231885);
}

/**
 * Paths отдаёт пути ко всему, что приложение держит на диске.
 */
export function Paths(): $CancellablePromise<$models.Paths> {
    return $Call.ByID(734719695);
}

/**
 * Rebuild сносит индекс и собирает заново. Возвращает сводку после пересборки,
 * чтобы интерфейсу не пришлось спрашивать её вторым вызовом.
 */
export function Rebuild(): $CancellablePromise<notes$0.Stats> {
    return $Call.ByID(1799458656);
}

/**
 * Reveal показывает файл или папку в Finder.
 * 
 * Через `open -R`, а не `open`: у файла второе открыло бы его в редакторе по
 * умолчанию, а спрашивают тут именно «где он лежит».
 */
export function Reveal(path: string): $CancellablePromise<void> {
    return $Call.ByID(3170638400, path);
}

/**
 * Stats отдаёт сводку о хранилище: сколько чего и сколько весит индекс.
 */
export function Stats(): $CancellablePromise<notes$0.Stats> {
    return $Call.ByID(2288088444);
}
