// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Keymap — сервис Wails: раскладка клавиш.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Load отдаёт раскладку: умолчания, поверх которых легло содержимое файла.
 * 
 * Слияние, а не замена: файл может описывать одно сочетание, и остальные
 * должны продолжать работать. Пустая строка вместо команды снимает привязку —
 * иначе отказаться от умолчания было бы нечем.
 */
export function Load(): $CancellablePromise<{ [_ in string]?: { [_ in string]?: string } | null } | null> {
    return $Call.ByID(216875340);
}

/**
 * Path возвращает путь к файлу — интерфейсу есть что показать человеку.
 */
export function Path(): $CancellablePromise<string> {
    return $Call.ByID(814934903);
}

/**
 * Reset возвращает раскладку к умолчаниям.
 */
export function Reset(): $CancellablePromise<void> {
    return $Call.ByID(2029971215);
}

/**
 * Save записывает раскладку целиком.
 */
export function Save(raw: string): $CancellablePromise<void> {
    return $Call.ByID(1938835149, raw);
}
