// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Build — что за сборка запущена. Показывается в разделе «О программе».
 */
export interface Build {
    /**
     * Revision и Time берутся из vcs-меток, которые Go кладёт в бинарник сам.
     * Своей переменной версии у проекта нет: приложение собирается из
     * исходников на этой же машине, и коммит опознаёт сборку точнее номера.
     */
    "Revision": string;
    "Time": string;
    "Modified": boolean;
    "Go": string;
    "Wails": string;

    /**
     * Binary — путь к запущенному исполняемому файлу.
     */
    "Binary": string;
}

/**
 * GitSettings — то, что настройки показывают про историю.
 */
export interface GitSettings {
    /**
     * WindowSeconds — окно автокоммита. Ноль означает коммит на каждое
     * сохранение.
     */
    "WindowSeconds": number;
}

/**
 * Paths — где что лежит. Из настроек эти пути открываются в Finder.
 */
export interface Paths {
    "Vault": string;
    "Config": string;
    "Keymap": string;
    "Vaults": string;
    "Index": string;
    "MCP": string;
}
