// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Notes — сервис Wails поверх internal/notes.
 * 
 * Тонкая обёртка и ничего больше: каждый метод разбирает аргументы и зовёт
 * слой ниже. Бизнес-правила живут в internal/notes, потому что тот же код
 * нужен tasker-mcp, который про Wails не знает (CLAUDE.md, инвариант 3).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as index$0 from "../index/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notes$0 from "../notes/models.js";

/**
 * Create заводит заметку и возвращает её строку индекса.
 */
export function Create(title: string, notebook: string): $CancellablePromise<index$0.Record> {
    return $Call.ByID(1827270868, title, notebook).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Get читает заметку целиком: тело, исходящие ссылки и бэклинки.
 */
export function Get(id: string): $CancellablePromise<notes$0.Note> {
    return $Call.ByID(4086263884, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Notebooks возвращает дерево ноутбуков со счётчиками.
 */
export function Notebooks(): $CancellablePromise<index$0.Notebook[]> {
    return $Call.ByID(1054013206).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Save сохраняет заголовок и тело открытой заметки.
 * 
 * Отдельный метод, а не общий Update: редактор сохраняет ровно эти два поля, и
 * пропускать их через общий путь значит рисковать задеть остальные.
 */
export function Save(id: string, title: string, body: string): $CancellablePromise<index$0.Record> {
    return $Call.ByID(3793980845, id, title, body).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Search находит заметки по запросу на языке из SPEC §8.5.
 * Пустой запрос означает все заметки.
 */
export function Search(query: string, limit: number): $CancellablePromise<notes$0.Note[]> {
    return $Call.ByID(252173164, query, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SetStatus меняет статус заметки.
 */
export function SetStatus(id: string, status: string): $CancellablePromise<index$0.Record> {
    return $Call.ByID(2988377314, id, status).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Tags возвращает теги со счётчиками.
 */
export function Tags(): $CancellablePromise<index$0.Tag[]> {
    return $Call.ByID(351009625).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Trash переносит заметку в корзину.
 */
export function Trash(id: string): $CancellablePromise<void> {
    return $Call.ByID(1638432474, id);
}

// Private type creation functions
const $$createType0 = index$0.Record.createFrom;
const $$createType1 = notes$0.Note.createFrom;
const $$createType2 = index$0.Notebook.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType1);
const $$createType5 = index$0.Tag.createFrom;
const $$createType6 = $Create.Array($$createType5);
