// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Notes — сервис Wails поверх internal/notes.
 * 
 * Тонкая обёртка и ничего больше: каждый метод разбирает аргументы и зовёт
 * слой ниже. Бизнес-правила живут в internal/notes, потому что тот же код
 * нужен tasker-mcp, который про Wails не знает (CLAUDE.md, инвариант 3).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as index$0 from "../index/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notes$0 from "../notes/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddAttachment сохраняет вложение из вебвью.
 * 
 * Данные приходят строкой base64, а не массивом байтов: через биндинги массив
 * на несколько мегабайт едет числами по одному, и вставка скриншота
 * превращается в мегабайты JSON.
 */
export function AddAttachment(filename: string, encoded: string): $CancellablePromise<$models.Attachment> {
    return $Call.ByID(1954921214, filename, encoded);
}

/**
 * ApplyTemplate накладывает шаблон на заметку и говорит, куда поставить каретку.
 */
export function ApplyTemplate(id: string, template: string): $CancellablePromise<notes$0.TemplateResult> {
    return $Call.ByID(311696782, id, template);
}

/**
 * Counts возвращает счётчики для верхних пунктов сайдбара.
 */
export function Counts(): $CancellablePromise<index$0.Counts> {
    return $Call.ByID(1597084356);
}

/**
 * Create заводит заметку и возвращает её строку индекса.
 */
export function Create(title: string, notebook: string): $CancellablePromise<index$0.Record> {
    return $Call.ByID(1827270868, title, notebook);
}

/**
 * CreateNotebook заводит пустой ноутбук.
 */
export function CreateNotebook(path: string): $CancellablePromise<void> {
    return $Call.ByID(754186437, path);
}

/**
 * Delete удаляет заметку насовсем. Только из корзины и только отсюда: агенту
 * это не дано (docs/MCP.md §4).
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3028446315, id);
}

/**
 * DeleteNotebook переносит содержимое ноутбука в корзину и убирает папку.
 */
export function DeleteNotebook(path: string): $CancellablePromise<index$0.Record[] | null> {
    return $Call.ByID(1355849942, path);
}

/**
 * DeleteTag убирает тег из всех заметок одним коммитом, вместе с корзиной.
 */
export function DeleteTag(name: string): $CancellablePromise<index$0.Record[] | null> {
    return $Call.ByID(1338820345, name);
}

/**
 * Duplicate создаёт копию заметки рядом с оригиналом.
 */
export function Duplicate(id: string): $CancellablePromise<index$0.Record> {
    return $Call.ByID(2338619345, id);
}

/**
 * Get читает заметку целиком: тело, исходящие ссылки и бэклинки.
 */
export function Get(id: string): $CancellablePromise<notes$0.Note> {
    return $Call.ByID(4086263884, id);
}

/**
 * Move переносит заметку в другой ноутбук. Пустая строка — корень vault.
 */
export function Move(id: string, notebook: string): $CancellablePromise<index$0.Record> {
    return $Call.ByID(2195879325, id, notebook);
}

export function MoveMany(ids: string[] | null, notebook: string): $CancellablePromise<index$0.Record[] | null> {
    return $Call.ByID(3874796650, ids, notebook);
}

/**
 * Notebooks возвращает дерево ноутбуков со счётчиками.
 */
export function Notebooks(): $CancellablePromise<index$0.Notebook[] | null> {
    return $Call.ByID(1054013206);
}

/**
 * RenameNotebook переименовывает ноутбук вместе со всем содержимым.
 */
export function RenameNotebook($from: string, to: string): $CancellablePromise<index$0.Record[] | null> {
    return $Call.ByID(258134739, $from, to);
}

/**
 * RenameTag переименовывает тег во всех заметках одним коммитом (SPEC §8.2).
 */
export function RenameTag($from: string, to: string): $CancellablePromise<index$0.Record[] | null> {
    return $Call.ByID(2644956362, $from, to);
}

/**
 * Restore возвращает заметку из корзины туда, откуда она уехала.
 */
export function Restore(id: string): $CancellablePromise<index$0.Record> {
    return $Call.ByID(3499809458, id);
}

/**
 * Save сохраняет заголовок и тело открытой заметки.
 * 
 * Отдельный метод, а не общий Update: редактор сохраняет ровно эти два поля, и
 * пропускать их через общий путь значит рисковать задеть остальные.
 */
export function Save(id: string, title: string, body: string): $CancellablePromise<index$0.Record> {
    return $Call.ByID(3793980845, id, title, body);
}

/**
 * Search находит заметки по запросу на языке из SPEC §8.5.
 * 
 * Пустой запрос означает все заметки. hideCompleted убирает завершённое и
 * брошенное — так список ноутбука выглядит по умолчанию (SPEC §8.3).
 */
export function Search(query: string, limit: number, hideCompleted: boolean, sortField: string, reversed: boolean): $CancellablePromise<notes$0.Note[] | null> {
    return $Call.ByID(252173164, query, limit, hideCompleted, sortField, reversed);
}

/**
 * SetPinned закрепляет заметку или снимает закрепление.
 */
export function SetPinned(id: string, pinned: boolean): $CancellablePromise<index$0.Record> {
    return $Call.ByID(3728356338, id, pinned);
}

export function SetPinnedMany(ids: string[] | null, pinned: boolean): $CancellablePromise<index$0.Record[] | null> {
    return $Call.ByID(1958385413, ids, pinned);
}

/**
 * SetStatus меняет статус заметки.
 */
export function SetStatus(id: string, status: string): $CancellablePromise<index$0.Record> {
    return $Call.ByID(2988377314, id, status);
}

export function SetStatusMany(ids: string[] | null, status: string): $CancellablePromise<index$0.Record[] | null> {
    return $Call.ByID(2900221013, ids, status);
}

/**
 * SetTagColor выбирает цвет тега из палитры; -1 снимает выбор.
 */
export function SetTagColor(name: string, color: number): $CancellablePromise<void> {
    return $Call.ByID(2272116631, name, color);
}

/**
 * SetTags заменяет теги заметки целиком: поле под заголовком правится так.
 */
export function SetTags(id: string, tags: string[] | null): $CancellablePromise<index$0.Record> {
    return $Call.ByID(3408374185, id, tags);
}

/**
 * Tags возвращает теги со счётчиками.
 */
export function Tags(): $CancellablePromise<index$0.Tag[] | null> {
    return $Call.ByID(351009625);
}

/**
 * Tasks — что сейчас в работе: active и onHold из всех ноутбуков.
 * 
 * Отдельный метод, а не запрос: язык соединяет условия только через И, а здесь
 * нужно ИЛИ по статусам. Это псевдо-ноутбук «Активные», главный экран рабочего
 * дня (SPEC §8.3).
 */
export function Tasks(limit: number): $CancellablePromise<notes$0.Note[] | null> {
    return $Call.ByID(4129384194, limit);
}

/**
 * Templates перечисляет шаблоны из папки templates/ (SPEC §8.10).
 */
export function Templates(): $CancellablePromise<notes$0.Template[] | null> {
    return $Call.ByID(3688156363);
}

/**
 * Trash переносит заметку в корзину.
 */
export function Trash(id: string): $CancellablePromise<void> {
    return $Call.ByID(1638432474, id);
}

export function TrashMany(ids: string[] | null): $CancellablePromise<index$0.Record[] | null> {
    return $Call.ByID(544364605, ids);
}

/**
 * Trashed возвращает содержимое корзины.
 */
export function Trashed(limit: number): $CancellablePromise<notes$0.Note[] | null> {
    return $Call.ByID(3456183915, limit);
}
