// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings — сервис Wails: хранение настроек интерфейса.
 * 
 * Содержимое для Go непрозрачно и хранится как есть. Это не отступление от
 * «вся логика в Go»: ширины колонок, порядок сортировки и развёрнутые ветки
 * дерева — состояние интерфейса, которого в Go нет и быть не должно. Типизируй
 * мы его здесь, каждая новая настройка требовала бы правки Go, перегенерации
 * биндингов и пересборки — ради числа, которое Go никогда не прочитает.
 * 
 * Агенту это недоступно: писать в config.json ему не дано (docs/MCP.md §4), и
 * сервис живёт только в приложении.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Load читает настройки. Пустая строка означает, что их ещё нет.
 */
export function Load(): $CancellablePromise<string> {
    return $Call.ByID(322383110);
}

/**
 * Save записывает настройки.
 */
export function Save(raw: string): $CancellablePromise<void> {
    return $Call.ByID(2217450019, raw);
}
