// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Vaults — сервис Wails: какая папка открыта и как сменить её на другую.
 * 
 * Смена требует перезапуска, и это осознанно. Переоткрыть хранилище на лету
 * значит погасить и поднять заново индекс, watcher, git и открытый буфер
 * редактора — четыре подсистемы, каждая со своим временем жизни. Ради
 * действия, которое делают раз в полгода, это не окупается.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Choose открывает системный диалог выбора папки и запоминает выбранное.
 * 
 * Возвращает выбранный путь; ErrNoVaultChosen, если диалог закрыли. Само
 * приложение при этом продолжает работать со старой папкой — переезд
 * случится при следующем запуске.
 */
export function Choose(): $CancellablePromise<string> {
    return $Call.ByID(199143291);
}

/**
 * Current отдаёт записанный путь. Пустая строка — записи ещё нет.
 * 
 * Читает это и cmd/tasker при запуске, поэтому метод не должен ничего
 * требовать от Wails.
 */
export function Current(): $CancellablePromise<string> {
    return $Call.ByID(2233944571);
}

/**
 * Forget убирает папку из недавних. Текущую забыть нельзя.
 */
export function Forget(path: string): $CancellablePromise<void> {
    return $Call.ByID(1425337387, path);
}

/**
 * Path возвращает путь к vaults.json — интерфейсу есть что показать.
 */
export function Path(): $CancellablePromise<string> {
    return $Call.ByID(372315625);
}

/**
 * Recent отдаёт недавние папки без текущей.
 */
export function Recent(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2555312689);
}

/**
 * Restart перезапускает приложение, чтобы смена папки вступила в силу.
 * 
 * Запускается новый экземпляр, и только потом гасится текущий: если запуск не
 * удался, человек останется в работающем приложении, а не перед пустым
 * экраном. Гашение обязательно, и обязательно через shutdown: без него на
 * экране оказывались два приложения разом — новое с новой папкой и старое со
 * старой, — а прямой выход мимо хука закрытия потерял бы буфер редактора.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(2048718189);
}

/**
 * Reveal показывает папку в Finder.
 */
export function Reveal(path: string): $CancellablePromise<void> {
    return $Call.ByID(2135256351, path);
}

/**
 * Switch записывает новую текущую папку.
 * 
 * Проверяет, что это папка, до записи: узнать о том, что путь негодный, при
 * следующем запуске — значит получить приложение, которое не открывается.
 */
export function Switch(path: string): $CancellablePromise<void> {
    return $Call.ByID(4259045890, path);
}
