// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as index$0 from "../index/models.js";

/**
 * Note — заметка целиком: строка индекса, тело и связи.
 */
export interface Note {
    "ID": string;

    /**
     * относительно корня vault, всегда со слэшами
     */
    "Path": string;
    "Notebook": string;
    "Title": string;
    "Status": string;
    "Pinned": boolean;
    "Created": string;
    "Updated": string;
    "ModTime": string;
    "Size": number;
    "NumTasks": number;
    "NumDone": number;
    "Excerpt": string;
    "Trashed": boolean;
    "Tags": string[] | null;
    "Body": string;
    "Links": index$0.Record[] | null;
    "Backlinks": index$0.Record[] | null;
}
