// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as index$0 from "../index/models.js";

/**
 * Note — заметка целиком: строка индекса, тело и связи.
 */
export interface Note {
    "ID": string;

    /**
     * относительно корня vault, всегда со слэшами
     */
    "Path": string;
    "Notebook": string;
    "Title": string;
    "Status": string;
    "Pinned": boolean;
    "Created": string;
    "Updated": string;
    "ModTime": string;
    "Size": number;
    "NumTasks": number;
    "NumDone": number;
    "Excerpt": string;
    "Trashed": boolean;

    /**
     * Origin повторяет поле frontmatter: заметку от агента список показывает
     * иначе, а без колонки в индексе это пришлось бы выяснять чтением файла.
     */
    "Origin": string;
    "Tags": string[] | null;
    "Body": string;
    "Links": index$0.Record[] | null;
    "Backlinks": index$0.Record[] | null;
}

/**
 * Stats — сводка о хранилище для экрана настроек.
 */
export interface Stats {
    /**
     * Active — заметки со статусом active или onHold, кроме корзины.
     */
    "Active": number;

    /**
     * All — все заметки, кроме корзины.
     */
    "All": number;

    /**
     * Agent — заведённые агентом, кроме корзины.
     */
    "Agent": number;

    /**
     * Trashed — то, что лежит в корзине.
     */
    "Trashed": number;

    /**
     * IndexSize — размер файла индекса в байтах.
     */
    "IndexSize": number;

    /**
     * AgentLast — когда агент последний раз писал. Нулевое время — не писал.
     */
    "AgentLast": string;

    /**
     * Notebooks — сколько ноутбуков, считая пустые.
     */
    "Notebooks": number;

    /**
     * Tags — сколько разных тегов.
     */
    "Tags": number;
}

/**
 * Template — шаблон, каким его показывают в пикере.
 */
export interface Template {
    /**
     * Name — имя файла без расширения: по нему шаблон ищут в пикере.
     */
    "Name": string;

    /**
     * Path — путь от корня хранилища.
     */
    "Path": string;

    /**
     * Title — заголовок будущей заметки из блока _template, если он задан.
     */
    "Title": string;

    /**
     * Preview — начало тела, чтобы было видно, что именно вставится.
     */
    "Preview": string;
}

/**
 * TemplateResult — заметка после применения шаблона и место для каретки.
 */
export interface TemplateResult {
    "Record": index$0.Record;

    /**
     * Cursor — смещение каретки в теле; -1, если шаблон её не задавал.
     */
    "Cursor": number;
}
