// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Notebook — ноутбук и то, что о нём знает индекс.
 */
export class Notebook {
    /**
     * Path — путь относительно корня vault. Пустая строка — сам корень.
     */
    "Path": string;

    /**
     * Count — заметок непосредственно в этом ноутбуке, без вложенных.
     * Свёрнутый ноутбук показывает сумму с детьми, и считает её интерфейс
     * (SPEC §8.1).
     */
    "Count": number;

    /**
     * Children — пути дочерних ноутбуков, на один уровень вниз.
     */
    "Children": string[];

    /** Creates a new Notebook instance. */
    constructor($$source: Partial<Notebook> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }
        if (!("Children" in $$source)) {
            this["Children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notebook instance from a string or object.
     */
    static createFrom($$source: any = {}): Notebook {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Children" in $$parsedSource) {
            $$parsedSource["Children"] = $$createField2_0($$parsedSource["Children"]);
        }
        return new Notebook($$parsedSource as Partial<Notebook>);
    }
}

/**
 * Record — то, что индекс хранит про заметку.
 */
export class Record {
    "ID": string;

    /**
     * относительно корня vault, всегда со слэшами
     */
    "Path": string;
    "Notebook": string;
    "Title": string;
    "Status": string;
    "Pinned": boolean;
    "Created": string;
    "Updated": string;
    "ModTime": string;
    "Size": number;
    "NumTasks": number;
    "NumDone": number;
    "Excerpt": string;
    "Trashed": boolean;
    "Tags": string[];
    "Links": string[];

    /**
     * Body уходит в полнотекстовый индекс и обратно не читается: таблица
     * contentless, содержимое в ней не хранится.
     */
    "Body": string;

    /** Creates a new Record instance. */
    constructor($$source: Partial<Record> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Notebook" in $$source)) {
            this["Notebook"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("Pinned" in $$source)) {
            this["Pinned"] = false;
        }
        if (!("Created" in $$source)) {
            this["Created"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("Updated" in $$source)) {
            this["Updated"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("ModTime" in $$source)) {
            this["ModTime"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }
        if (!("NumTasks" in $$source)) {
            this["NumTasks"] = 0;
        }
        if (!("NumDone" in $$source)) {
            this["NumDone"] = 0;
        }
        if (!("Excerpt" in $$source)) {
            this["Excerpt"] = "";
        }
        if (!("Trashed" in $$source)) {
            this["Trashed"] = false;
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }
        if (!("Links" in $$source)) {
            this["Links"] = [];
        }
        if (!("Body" in $$source)) {
            this["Body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     */
    static createFrom($$source: any = {}): Record {
        const $$createField14_0 = $$createType0;
        const $$createField15_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField14_0($$parsedSource["Tags"]);
        }
        if ("Links" in $$parsedSource) {
            $$parsedSource["Links"] = $$createField15_0($$parsedSource["Links"]);
        }
        return new Record($$parsedSource as Partial<Record>);
    }
}

/**
 * Tag — тег и число заметок с ним.
 */
export class Tag {
    "Name": string;
    "Count": number;
    "Color": string;

    /** Creates a new Tag instance. */
    constructor($$source: Partial<Tag> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }
        if (!("Color" in $$source)) {
            this["Color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     */
    static createFrom($$source: any = {}): Tag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag($$parsedSource as Partial<Tag>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
