// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Notebook — ноутбук и то, что о нём знает индекс.
 */
export interface Notebook {
    /**
     * Path — путь относительно корня vault. Пустая строка — сам корень.
     */
    "Path": string;

    /**
     * Count — заметок непосредственно в этом ноутбуке, без вложенных.
     * Свёрнутый ноутбук показывает сумму с детьми, и считает её интерфейс
     * (SPEC §8.1).
     */
    "Count": number;

    /**
     * Children — пути дочерних ноутбуков, на один уровень вниз.
     */
    "Children": string[] | null;
}

/**
 * Record — то, что индекс хранит про заметку.
 */
export interface Record {
    "ID": string;

    /**
     * относительно корня vault, всегда со слэшами
     */
    "Path": string;
    "Notebook": string;
    "Title": string;
    "Status": string;
    "Pinned": boolean;
    "Created": string;
    "Updated": string;
    "ModTime": string;
    "Size": number;
    "NumTasks": number;
    "NumDone": number;
    "Excerpt": string;
    "Trashed": boolean;
    "Tags": string[] | null;
    "Links": string[] | null;

    /**
     * Body уходит в полнотекстовый индекс и обратно не читается: таблица
     * contentless, содержимое в ней не хранится.
     */
    "Body": string;
}

/**
 * Tag — тег и число заметок с ним.
 */
export interface Tag {
    "Name": string;
    "Count": number;
    "Color": string;
}
