// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Counts — счётчики для верхних пунктов сайдбара (макет T5).
 * 
 * Одним запросом, а не четырьмя поисками: цифры пересчитываются на каждое
 * изменение в vault, и гонять ради них полный SELECT четыре раза незачем.
 */
export interface Counts {
    /**
     * Active — заметки со статусом active или onHold, кроме корзины.
     */
    "Active": number;

    /**
     * All — все заметки, кроме корзины.
     */
    "All": number;

    /**
     * Agent — заведённые агентом, кроме корзины.
     */
    "Agent": number;

    /**
     * Trashed — то, что лежит в корзине.
     */
    "Trashed": number;
}

/**
 * Notebook — ноутбук и то, что о нём знает индекс.
 */
export interface Notebook {
    /**
     * Path — путь относительно корня vault. Пустая строка — сам корень.
     */
    "Path": string;

    /**
     * Count — заметок непосредственно в этом ноутбуке, без вложенных.
     * Свёрнутый ноутбук показывает сумму с детьми, и считает её интерфейс
     * (SPEC §8.1).
     */
    "Count": number;

    /**
     * Children — пути дочерних ноутбуков, на один уровень вниз.
     */
    "Children": string[] | null;
}

/**
 * Record — то, что индекс хранит про заметку.
 */
export interface Record {
    "ID": string;

    /**
     * относительно корня vault, всегда со слэшами
     */
    "Path": string;
    "Notebook": string;
    "Title": string;
    "Status": string;
    "Pinned": boolean;
    "Created": string;
    "Updated": string;
    "ModTime": string;
    "Size": number;
    "NumTasks": number;
    "NumDone": number;
    "Excerpt": string;
    "Trashed": boolean;

    /**
     * Origin повторяет поле frontmatter: заметку от агента список показывает
     * иначе, а без колонки в индексе это пришлось бы выяснять чтением файла.
     */
    "Origin": string;
    "Tags": string[] | null;
    "Links": string[] | null;

    /**
     * Body уходит в полнотекстовый индекс и обратно не читается: таблица
     * contentless, содержимое в ней не хранится.
     */
    "Body": string;
}

/**
 * Tag — тег и число заметок с ним.
 */
export interface Tag {
    "Name": string;
    "Count": number;
    "Color": string;
}
